import type { WorkspaceProject } from "~/types/workspace";

export const workspaceProjects: WorkspaceProject[] = [
  {
    id: "rental",
    name: "Rental Property Management",
    slug: "rental",
    category: "Full-Stack",
    description: "End-to-end rental & tenant management system with room tracking, meter readings, automated invoices, and tenant payment portal.",
    longDescription: "A comprehensive property management platform built for landlords and property managers. Features automated utility calculations, Khmer QR/Bakong payment integrations, lease contract tracking, and tenant mobile access.",
    progress: 90,
    status: "Active",
    priority: "High",
    techStack: {
      backend: ["Bun", "Hono", "Prisma"],
      frontend: ["Next.js 14", "shadcn/ui", "Tailwind CSS"],
      mobile: ["React Native", "Expo 54"],
      database: ["PostgreSQL 17"],
      infra: ["Docker", "MinIO S3"],
    },
    keyFeatures: [
      "Room & unit inventory management with floor plans",
      "Automated utility meter calculation (water & power)",
      "Tenant invoicing with PDF generation and QR payment",
      "Tenant mobile companion app with notification support",
      "Financial reporting and occupancy rate metrics",
    ],
    milestones: [
      { title: "Core CRUD & Multi-room data model", completed: true },
      { title: "Invoice & Utility billing engine", completed: true },
      { title: "Expo Mobile tenant app v1", completed: true },
      { title: "Bakong payment gateway webhooks", completed: true },
      { title: "Automated monthly rent roll SMS/Telegram alerts", completed: false },
    ],
    graphStats: { nodes: 2290, edges: 5400 },
    ports: [3000, 3001, 5432],
    path: "rental/",
    quickCommands: [
      { label: "Frontend", cmd: "cd rental/frontend && bun run dev" },
      { label: "Backend", cmd: "cd rental/backend && bun run dev" },
      { label: "Mobile", cmd: "cd rental/mobile && bun run start" },
    ],
    lastUpdated: "Today",
  },
  {
    id: "designkit",
    name: "DesignKit (React & Vue/Nuxt)",
    slug: "designkit",
    category: "UI & Components",
    description: "Apple-inspired, accessible React & Vue component system with Tailwind CSS, Base UI, and Reka UI primitives.",
    longDescription: "A unified component design system offering cross-framework components for React 19 and Vue 3 / Nuxt 4. Focuses on polished micro-interactions, Apple HIG aesthetics, dark mode support, and seamless copy-paste registry.",
    progress: 85,
    status: "Active",
    priority: "High",
    techStack: {
      frontend: ["React 19", "Vue 3", "Nuxt 4", "Vite", "Tailwind CSS 4"],
      tools: ["Base UI", "Reka UI", "Radix Primitives", "Lucide Icons"],
      infra: ["Changesets", "Vitest", "Vercel"],
    },
    keyFeatures: [
      "60+ Accessible UI primitives in React & Vue",
      "Apple-inspired design language with fluid spring easings",
      "Interactive component catalog with copy-paste CLI registry",
      "Dark / Light / System auto color modes",
      "Integrated workspace progress visualization dashboard",
    ],
    milestones: [
      { title: "React 19 component library core", completed: true },
      { title: "Nuxt 4 / Vue 3 shadcn integration", completed: true },
      { title: "Component registry JSON generator", completed: true },
      { title: "Interactive documentation showcase", completed: true },
      { title: "Figma design token synchronization", completed: false },
    ],
    graphStats: { nodes: 27529, edges: 65339 },
    ports: [3312, 5173],
    path: "designkit/",
    quickCommands: [
      { label: "Nuxt App", cmd: "npm run --prefix designkit/shadcn-vue dev" },
      { label: "React Showcase", cmd: "npm run --prefix designkit dev" },
      { label: "Build Lib", cmd: "npm run --prefix designkit build:lib" },
    ],
    lastUpdated: "Just now",
  },
  {
    id: "foodie",
    name: "Foodie — World Recipe & Meal Planner",
    slug: "foodie",
    category: "Full-Stack",
    description: "Global recipe discovery platform with intelligent grocery budgeting, step-by-step cooking timers, and nutrition tracking.",
    longDescription: "A modern culinary ecosystem featuring curated world recipes, smart pantry inventory tracking, dietary filtering, and personalized weekly meal planning with automated grocery list export.",
    progress: 78,
    status: "In Progress",
    priority: "High",
    techStack: {
      backend: ["TypeScript", "Express 5", "Prisma 7"],
      frontend: ["Next.js 16", "React 19", "Tailwind CSS"],
      mobile: ["React Native 0.81", "Expo 54"],
      database: ["PostgreSQL 17"],
      infra: ["MinIO S3", "Redis"],
    },
    keyFeatures: [
      "Rich recipe taxonomy with multi-language ingredients",
      "Interactive step-by-step cooking mode with voice countdown timers",
      "Weekly meal scheduler with automated grocery cart sync",
      "Nutrition breakdown calculator (macros, calories, allergens)",
      "Offline-first mobile client with local recipe caching",
    ],
    milestones: [
      { title: "Recipe schema & Prisma ORM model", completed: true },
      { title: "Next.js 16 Web application UI", completed: true },
      { title: "Expo mobile cooking screen", completed: true },
      { title: "Nutrition macro calculation engine", completed: true },
      { title: "AI Recipe generation from pantry photo", completed: false },
    ],
    graphStats: { nodes: 693, edges: 1600 },
    ports: [3002, 5000],
    path: "foodie/",
    quickCommands: [
      { label: "Web", cmd: "cd foodie/frontend && npm run dev" },
      { label: "Backend", cmd: "cd foodie/backend && npm run dev" },
    ],
    lastUpdated: "1 day ago",
  },
  {
    id: "group-expense",
    name: "Group Expense — Splitwise Clone",
    slug: "group-expense",
    category: "Full-Stack",
    description: "Collaborative trip and group expense splitter with debt simplification algorithms and multi-currency support.",
    longDescription: "Streamlines expense sharing for friends, trips, and roommates. Features optimal debt settlement graph algorithms, OCR receipt scanning, and automated balance reminders.",
    progress: 82,
    status: "In Progress",
    priority: "High",
    techStack: {
      backend: ["TypeScript", "NestJS 10", "Prisma 5"],
      frontend: ["Next.js 16", "React 19", "shadcn/ui"],
      mobile: ["React Native 0.81", "Expo 54"],
      database: ["PostgreSQL 17"],
      infra: ["Redis", "RabbitMQ"],
    },
    keyFeatures: [
      "Multi-participant expense split (equal, exact, percentage, shares)",
      "Min-cash-flow algorithm for minimal settlement transactions",
      "Group activity feed with realtime updates",
      "Multi-currency conversion with live exchange rates",
      "Receipt attachment upload via S3 MinIO",
    ],
    milestones: [
      { title: "NestJS architecture & balance calculation", completed: true },
      { title: "Next.js 16 web dashboard", completed: true },
      { title: "Mobile bill split workflow", completed: true },
      { title: "S3 receipt upload integration", completed: true },
      { title: "Bakong settlement deep link", completed: false },
    ],
    graphStats: { nodes: 713, edges: 1750 },
    ports: [3003, 4000],
    path: "group-expense/",
    quickCommands: [
      { label: "Web", cmd: "cd group-expense/frontend && npm run dev" },
      { label: "API", cmd: "cd group-expense/backend && npm run start:dev" },
    ],
    lastUpdated: "2 days ago",
  },
  {
    id: "ev-station-kh",
    name: "EV Station Cambodia",
    slug: "ev-station-kh",
    category: "Full-Stack",
    description: "Cambodia EV charging station locator, real-time availability map, charger connector filters, and reservation booking.",
    longDescription: "Geospatial platform tailored for electric vehicle drivers in Cambodia. Features PostGIS spatial queries, station operating hours, plug compatibility (CCS2, Type 2, GB/T, CHAdeMO), and route charger planning.",
    progress: 72,
    status: "In Progress",
    priority: "Medium",
    techStack: {
      backend: ["TypeScript", "NestJS 10", "Prisma 5", "PostGIS"],
      frontend: ["Next.js 14", "Leaflet Maps", "shadcn/ui"],
      mobile: ["React Native 0.76", "Expo 54"],
      database: ["PostgreSQL 17 + PostGIS"],
    },
    keyFeatures: [
      "Interactive map with station clusters and live filtering",
      "Connector compatibility selector & power kW ratings",
      "Distance & ETA calculation using geospatial coordinates",
      "User reviews, photo uploads, and station status reporting",
      "Turn-by-turn navigation link to Google Maps / Apple Maps",
    ],
    milestones: [
      { title: "PostGIS database schema & station seeding", completed: true },
      { title: "Leaflet map frontend with connector filters", completed: true },
      { title: "Mobile station finder with GPS location", completed: true },
      { title: "Realtime charger occupancy simulation", completed: false },
      { title: "Slot reservation & prepayment", completed: false },
    ],
    graphStats: { nodes: 868, edges: 1950 },
    ports: [3004, 4001],
    path: "ev-station-kh/",
    quickCommands: [
      { label: "Frontend", cmd: "cd ev-station-kh/frontend && npm run dev" },
      { label: "Backend", cmd: "cd ev-station-kh/backend && npm run start:dev" },
    ],
    lastUpdated: "3 days ago",
  },
  {
    id: "asset-inventory",
    name: "StockFlow Asset & Inventory",
    slug: "asset-inventory",
    category: "Full-Stack",
    description: "Enterprise asset tracking, spare-part management, maintenance work-orders, and barcode/QR check-in/out.",
    longDescription: "A robust inventory and asset management system for equipment, IT hardware, and spare parts. Includes depreciation schedules, low-stock alerts, maintenance schedules, and audit trails.",
    progress: 85,
    status: "Active",
    priority: "High",
    techStack: {
      backend: ["Python 3.11", "FastAPI", "SQLAlchemy 2.0 (Async)"],
      frontend: ["Next.js 14", "shadcn/ui", "Recharts", "TanStack Table"],
      database: ["PostgreSQL 17", "Alembic Migrations"],
      infra: ["Docker Compose"],
    },
    keyFeatures: [
      "Asset lifecycle tracking (Purchase -> Active -> Maintenance -> Retired)",
      "Stock room multi-location bin allocation",
      "QR / Barcode scanner for rapid check-in and checkout",
      "Preventative maintenance scheduling and work orders",
      "Inventory valuation and reorder threshold alerts",
    ],
    milestones: [
      { title: "FastAPI async database layer & Alembic", completed: true },
      { title: "Next.js inventory tables with filtering", completed: true },
      { title: "Check-in/Checkout barcode scan workflow", completed: true },
      { title: "Analytics charts & asset valuation", completed: true },
      { title: "Automated low-stock supplier purchase order", completed: false },
    ],
    graphStats: { nodes: 1166, edges: 2800 },
    ports: [3005, 8001],
    path: "asset-inventory/",
    quickCommands: [
      { label: "Frontend", cmd: "cd asset-inventory/frontend && npm run dev" },
      { label: "API", cmd: "cd asset-inventory/backend && uvicorn app.main:app --reload --port 8001" },
    ],
    lastUpdated: "Aug 18",
  },
  {
    id: "broeksa",
    name: "Broeksa Career Aptitude Assessment",
    slug: "broeksa",
    category: "Full-Stack",
    description: "Bilingual (Khmer/English) career aptitude assessment platform with Holland Code (RIASEC) personality profiling and university major recommendations.",
    longDescription: "Helps Cambodian high school and university students discover suitable career paths based on psychometric tests, personality traits, and local university program databases.",
    progress: 88,
    status: "Active",
    priority: "High",
    techStack: {
      backend: ["TypeScript", "Hono 4", "Prisma 6", "Bun"],
      frontend: ["Next.js 15", "React 19", "ECharts", "Tailwind CSS"],
      database: ["PostgreSQL 17"],
    },
    keyFeatures: [
      "60-Question RIASEC aptitude assessment quiz",
      "Interactive ECharts radar & spider web visual reports",
      "Major & university database for Cambodia institutions",
      "Bilingual Khmer & English UI toggle",
      "PDF assessment certificate export",
    ],
    milestones: [
      { title: "Psychometric scoring algorithm & question bank", completed: true },
      { title: "Next.js 15 test taking UI with progress memory", completed: true },
      { title: "Result analysis radar charts with ECharts", completed: true },
      { title: "Khmer localized content & translations", completed: true },
      { title: "Career mentor booking integration", completed: false },
    ],
    graphStats: { nodes: 2189, edges: 5100 },
    ports: [3006, 8002],
    path: "broeksa/",
    quickCommands: [
      { label: "Web", cmd: "cd broeksa/frontend && bun run dev" },
      { label: "API", cmd: "cd broeksa/backend && bun run dev" },
    ],
    lastUpdated: "Aug 15",
  },
  {
    id: "wedding-management-system",
    name: "Wedding & Guest Management Suite",
    slug: "wedding-management-system",
    category: "Full-Stack",
    description: "Wedding planning suite with digital guest list, table seating arrangement, RSVP tracking, gift recording, and expense budgeting.",
    longDescription: "All-in-one wedding celebration manager. Features digital invitation generation with QR codes, table seat allocation drag-and-drop, monetary gift ledger, and vendor contracts.",
    progress: 80,
    status: "Active",
    priority: "Medium",
    techStack: {
      backend: ["Python", "FastAPI", "SQLAlchemy 2.0", "Alembic"],
      frontend: ["Next.js 15", "React 19", "Recharts", "shadcn/ui"],
      database: ["PostgreSQL 17"],
    },
    keyFeatures: [
      "Guest list RSVP tracking with dietary & headcount notes",
      "Visual table arrangement and seat layout builder",
      "Gift envelope ledger with currency totals",
      "Budget vs Actual expense breakdown charts",
      "SMS & Telegram reminder dispatch for guests",
    ],
    milestones: [
      { title: "Guest and table database schema", completed: true },
      { title: "Next.js 15 RSVP & invitation view", completed: true },
      { title: "Monetary gift registry ledger", completed: true },
      { title: "Table seating drag-and-drop builder", completed: true },
      { title: "Automated thank you message dispatcher", completed: false },
    ],
    graphStats: { nodes: 2501, edges: 5783 },
    ports: [3007, 8003],
    path: "wedding-management-system/",
    quickCommands: [
      { label: "Frontend", cmd: "cd wedding-management-system/frontend && npm run dev" },
      { label: "API", cmd: "cd wedding-management-system/backend && uvicorn app.main:app --reload" },
    ],
    lastUpdated: "Aug 19",
  },
  {
    id: "system-monitoring",
    name: "Rust System Monitoring & Metrics",
    slug: "system-monitoring",
    category: "Backend & API",
    description: "Ultra-fast infrastructure monitoring agent and alerting system built with Rust, Axum, sqlx, and Next.js.",
    longDescription: "Lightweight, high-throughput server telemetry collector and anomaly alert engine written in Rust. Collects CPU, memory, disk I/O, network traffic, and Docker container stats in sub-millisecond intervals.",
    progress: 65,
    status: "In Progress",
    priority: "Medium",
    techStack: {
      backend: ["Rust", "Axum", "tokio", "sqlx", "sysinfo"],
      frontend: ["Next.js", "React", "Tailwind CSS", "Recharts"],
      database: ["PostgreSQL 17"],
    },
    keyFeatures: [
      "Rust agent with sub-5MB memory footprint",
      "Real-time WebSocket streaming of server health metrics",
      "Configurable alert thresholds (CPU > 90%, disk exhaustion)",
      "Multi-node dashboard visualization",
      "Telegram & Discord webhook alert channels",
    ],
    milestones: [
      { title: "Rust metrics gathering daemon with sysinfo", completed: true },
      { title: "Axum REST & WebSocket streaming endpoints", completed: true },
      { title: "Next.js live metric chart frontend", completed: true },
      { title: "Historical metric aggregation in PostgreSQL", completed: false },
      { title: "Automated remediation script triggers", completed: false },
    ],
    graphStats: { nodes: 2642, edges: 5900 },
    ports: [3008, 9090],
    path: "system-monitoring/",
    quickCommands: [
      { label: "Rust Agent", cmd: "cd system-monitoring/backend && cargo run" },
      { label: "Dashboard", cmd: "cd system-monitoring/frontend && npm run dev" },
    ],
    lastUpdated: "Aug 10",
  },
  {
    id: "trading",
    name: "CFD & MT5 Trading Bot Platform",
    slug: "trading",
    category: "AI & Agents",
    description: "Algorithmic trading engine with MetaTrader 5 integration, market microservice pipeline, indicators, and risk management.",
    longDescription: "High-frequency quantitative trading framework featuring async market data ingest, technical indicator calculations (RSI, EMA, Bollinger, ATR), position sizing rules, and automated execution.",
    progress: 60,
    status: "In Progress",
    priority: "High",
    techStack: {
      backend: ["Python 3.11", "MetaTrader5", "asyncpg", "Redis"],
      frontend: ["Next.js", "React", "Lightweight Charts"],
      database: ["PostgreSQL 17", "TimescaleDB"],
      infra: ["Docker", "RabbitMQ"],
    },
    keyFeatures: [
      "Async MT5 broker connection & order execution pipeline",
      "Realtime tick & candle data persistence via Redis Streams",
      "Backtesting engine with slippage and spread simulation",
      "Dynamic risk per trade calculator and trailing stop loss",
      "Web telemetry console with live PnL and trade journal",
    ],
    milestones: [
      { title: "MT5 terminal connector & async event bus", completed: true },
      { title: "Indicator engine & strategy rule evaluator", completed: true },
      { title: "Order execution & risk guardrails", completed: true },
      { title: "Web dashboard with TradingView chart integration", completed: false },
      { title: "Multi-account portfolio balancer", completed: false },
    ],
    graphStats: { nodes: 2249, edges: 5125 },
    ports: [3009, 8004],
    path: "trading/",
    quickCommands: [
      { label: "Bot Engine", cmd: "cd trading && python -m src.main" },
      { label: "Web UI", cmd: "cd trading/frontend && npm run dev" },
    ],
    lastUpdated: "Aug 17",
  },
  {
    id: "export-services",
    name: "Export Services (PDF / Excel / CSV)",
    slug: "export-services",
    category: "Backend & API",
    description: "High-throughput asynchronous document generation microservice utilizing headless Puppeteer, BullMQ queues, and Redis.",
    longDescription: "Dedicated microservice used across the monorepo for generating pixel-perfect PDF reports, invoices, Excel spreadsheets, and CSV exports from HTML templates with worker concurrency.",
    progress: 90,
    status: "Active",
    priority: "High",
    techStack: {
      backend: ["TypeScript", "NestJS 10", "TypeORM", "Puppeteer"],
      infra: ["BullMQ", "Redis 8", "MinIO S3", "Docker"],
    },
    keyFeatures: [
      "Headless Chrome / Puppeteer PDF rendering engine",
      "Handlebars & Liquid HTML template engine with CSS styling",
      "Streaming large Excel (XLSX) generation with exceljs",
      "BullMQ background job queue with retry policies",
      "Direct MinIO S3 signed URL upload and callback webhooks",
    ],
    milestones: [
      { title: "NestJS microservice setup & template registry", completed: true },
      { title: "Puppeteer PDF rendering pool", completed: true },
      { title: "BullMQ asynchronous queue dispatcher", completed: true },
      { title: "S3 upload & presigned download links", completed: true },
      { title: "Template visual live-editor playground", completed: false },
    ],
    graphStats: { nodes: 455, edges: 1100 },
    ports: [4005],
    path: "export-services/",
    quickCommands: [
      { label: "Start Microservice", cmd: "cd export-services && npm run start:dev" },
      { label: "Worker Queue", cmd: "cd export-services && npm run start:worker" },
    ],
    lastUpdated: "Aug 12",
  },
  {
    id: "name-card-mobile",
    name: "CardLink — Digital NFC Business Card",
    slug: "name-card-mobile",
    category: "Mobile App",
    description: "Next-generation digital business card mobile app with custom QR codes, NFC card writing, contact exchange, and RevenueCat subscriptions.",
    longDescription: "Enables professionals to share contact details instantly via QR code or tap-to-share NFC cards. Includes contact CRM, custom theme branding, social media links, and vCard export.",
    progress: 85,
    status: "In Progress",
    priority: "Medium",
    techStack: {
      mobile: ["React Native 0.81", "Expo 54", "TypeScript"],
      backend: ["Firebase", "Backblaze B2", "Cloud Functions"],
      services: ["RevenueCat", "Google AdMob", "Zustand"],
    },
    keyFeatures: [
      "Custom branded business card designer (gradients, badges, avatars)",
      "Dynamic QR code generator with vector download",
      "NFC Tag read & write for physical card tapping",
      "One-tap 'Add to Apple Contacts / Google Contacts' vCard export",
      "RevenueCat Pro subscription tier & analytics",
    ],
    milestones: [
      { title: "Expo 54 mobile app core & card builder", completed: true },
      { title: "NFC tag writing module integration", completed: true },
      { title: "QR code sharing & public profile landing page", completed: true },
      { title: "RevenueCat in-app purchase setup", completed: true },
      { title: "Team / Corporate multi-card management", completed: false },
    ],
    graphStats: { nodes: 577, edges: 1400 },
    ports: [8081],
    path: "name-card-mobile/",
    quickCommands: [
      { label: "Start Expo", cmd: "cd name-card-mobile && npx expo start" },
      { label: "iOS Sim", cmd: "cd name-card-mobile && npx expo start --ios" },
    ],
    lastUpdated: "Aug 14",
  },
  {
    id: "subscription",
    name: "Subscription & Member Management",
    slug: "subscription",
    category: "Full-Stack",
    description: "Subscription tier management, billing cycle tracking, usage quotas, and member authorization dashboard.",
    longDescription: "Handles customer subscription lifecycles, tiered plan access, payment renewals, invoices, and feature flag entitlements across SaaS applications.",
    progress: 70,
    status: "In Progress",
    priority: "Medium",
    techStack: {
      backend: ["Python", "FastAPI", "SQLAlchemy 2.0"],
      frontend: ["React 19", "Vite", "Radix UI", "Tailwind CSS"],
      database: ["PostgreSQL 17"],
    },
    keyFeatures: [
      "Tiered membership plans (Free, Pro, Enterprise)",
      "Billing schedule generator (monthly, quarterly, annual)",
      "Usage-based quota enforcement and alerts",
      "Member access control and audit log",
    ],
    milestones: [
      { title: "Subscription data model & state machine", completed: true },
      { title: "FastAPI REST endpoints & JWT auth", completed: true },
      { title: "React 19 customer portal UI", completed: true },
      { title: "Payment gateway webhook listeners", completed: false },
    ],
    graphStats: { nodes: 961, edges: 2200 },
    ports: [3010, 8005],
    path: "subscription/",
    quickCommands: [
      { label: "Frontend", cmd: "cd subscription/frontend && npm run dev" },
      { label: "Backend", cmd: "cd subscription/backend && uvicorn app.main:app --reload" },
    ],
    lastUpdated: "Aug 11",
  },
  {
    id: "motomoto",
    name: "MotoMoto Autonomous AI Agent",
    slug: "motomoto",
    category: "AI & Agents",
    description: "Autonomous reasoning AI agent framework with inner voice monologue, trading market awareness, and ElevenLabs voice generation.",
    longDescription: "An experimental autonomous agent architecture featuring periodic self-reflection loops, memory retrieval, market sentiment awareness, and real-time audio voice output.",
    progress: 55,
    status: "Prototype",
    priority: "Medium",
    techStack: {
      backend: ["Python 3.11", "Ollama (qwen2.5)", "ElevenLabs API"],
      infra: ["Redis", "ChromaDB / Vector Memory"],
    },
    keyFeatures: [
      "Autonomous thought cycle (Observe -> Orient -> Decide -> Act)",
      "Local LLM inference via Ollama (qwen2.5-coder / qwen2.5:14b)",
      "Episodic and semantic memory recall",
      "ElevenLabs expressive voice narration synthesis",
      "Live terminal consciousness stream",
    ],
    milestones: [
      { title: "Agent loop & Ollama connector", completed: true },
      { title: "Inner voice streaming prompt architecture", completed: true },
      { title: "ElevenLabs TTS voice pipeline", completed: true },
      { title: "Autonomous web search & tool invocation", completed: false },
    ],
    graphStats: { nodes: 186, edges: 420 },
    ports: [8006],
    path: "motomoto/",
    quickCommands: [
      { label: "Run Agent", cmd: "cd motomoto && python -m agent.main" },
    ],
    lastUpdated: "Aug 08",
  },
  {
    id: "services",
    name: "Shared Infrastructure Services",
    slug: "services",
    category: "DevOps & Infra",
    description: "Centralized Docker Compose infrastructure powering all monorepo applications (PostgreSQL 17, MinIO S3, RabbitMQ 4, Redis 8).",
    longDescription: "Production-ready dockerized infrastructure stack designed for low-overhead local development and self-hosted Coolify production deployments.",
    progress: 100,
    status: "Production",
    priority: "High",
    techStack: {
      database: ["PostgreSQL 17 (Alpine)"],
      infra: ["MinIO S3 (AIStor)", "RabbitMQ 4", "Redis 8 (Alpine)", "Docker Compose"],
    },
    keyFeatures: [
      "PostgreSQL 17 on ports 5432 / 5433 with automated init scripts",
      "MinIO S3 object storage with console on 9100 / 9101",
      "RabbitMQ 4 message broker with management UI on 15672",
      "Redis 8 in-memory cache on port 6379",
      "Start scripts: start-dev.sh, start-prod.sh, start-minimal.sh",
    ],
    milestones: [
      { title: "PostgreSQL 17 container & healthchecks", completed: true },
      { title: "MinIO S3 enterprise setup", completed: true },
      { title: "RabbitMQ 4 queue clustering", completed: true },
      { title: "Redis 8 cache configuration", completed: true },
      { title: "Automated dev/prod startup scripts", completed: true },
    ],
    graphStats: { nodes: 12, edges: 30 },
    ports: [5432, 5433, 6379, 5672, 15672, 9100, 9101],
    path: "services/",
    quickCommands: [
      { label: "Start All", cmd: "cd services && ./start-dev.sh" },
      { label: "Start Minimal", cmd: "cd services && ./start-minimal.sh" },
      { label: "Stop All", cmd: "cd services && docker compose down" },
    ],
    lastUpdated: "Stable",
  },
  {
    id: "coolify",
    name: "Coolify PaaS & Production DevOps",
    slug: "coolify",
    category: "DevOps & Infra",
    description: "Self-hosted PaaS deployment runbooks, server migration scripts, SSL automation, and database backup orchestration.",
    longDescription: "Production deployment pipelines and maintenance runbooks for deploying all monorepo applications to `*.ramekhchhoeng.com` via Coolify.",
    progress: 95,
    status: "Production",
    priority: "High",
    techStack: {
      infra: ["Coolify PaaS", "Nginx", "Docker", "Bash Scripts", "Let's Encrypt SSL"],
    },
    keyFeatures: [
      "Automated Git-push deploy webhooks for web apps & microservices",
      "Zero-downtime container updates and rolling restarts",
      "Automated daily PostgreSQL & MinIO S3 backup sync",
      "Custom domain wildcard routing (*.ramekhchhoeng.com)",
      "Server resource health alerting and disaster recovery runbooks",
    ],
    milestones: [
      { title: "Coolify production server setup", completed: true },
      { title: "PostgreSQL & S3 backup cron scripts", completed: true },
      { title: "Wildcard SSL certificate provisioning", completed: true },
      { title: "Disaster recovery migration runbook", completed: true },
    ],
    graphStats: { nodes: 58, edges: 120 },
    path: "coolify/",
    quickCommands: [
      { label: "Check Status", cmd: "cd coolify && ./check-status.sh" },
    ],
    lastUpdated: "Stable",
  },
  {
    id: "portfolio",
    name: "Developer Portfolio & Showcase",
    slug: "portfolio",
    category: "Full-Stack",
    description: "Personal developer portfolio, interactive project showcases, technical blog, and live prompt engineering course.",
    longDescription: "Showcase website showcasing 25+ software engineering projects, system architecture diagrams, and interactive AI engineering articles.",
    progress: 85,
    status: "Active",
    priority: "Medium",
    techStack: {
      frontend: ["Next.js 15", "React 19", "Tailwind CSS", "Framer Motion"],
      tools: ["TypeScript", "Contentlayer / MDX", "Lucide"],
    },
    keyFeatures: [
      "Interactive 3D and spring animated project cards",
      "Technical blog with code syntax highlighting",
      "Live interactive Prompt Engineering course module",
      "Resume download and contact submission form",
      "Dark / Light theme with smooth transitions",
    ],
    milestones: [
      { title: "Portfolio hero & project gallery", completed: true },
      { title: "Prompt engineering course interactive page", completed: true },
      { title: "Mobile responsive navigation", completed: true },
      { title: "Interactive architecture graph visualizer", completed: false },
    ],
    graphStats: { nodes: 1977, edges: 4500 },
    ports: [3011],
    path: "portfolio/",
    quickCommands: [
      { label: "Dev Server", cmd: "cd portfolio && npm run dev" },
    ],
    lastUpdated: "Aug 16",
  },
  {
    id: "project-template",
    name: "Vben Admin Full-Stack Boilerplate",
    slug: "project-template",
    category: "Tools & Productivity",
    description: "Enterprise-grade starter boilerplate with Next.js 16 frontend, FastAPI backend, SQLAlchemy, and authentication modules.",
    longDescription: "Production-ready starter foundation for enterprise web applications. Includes role-based access control (RBAC), multi-tenant org support, table generators, and form builders.",
    progress: 80,
    status: "Active",
    priority: "Medium",
    techStack: {
      backend: ["Python", "FastAPI", "SQLAlchemy", "Alembic"],
      frontend: ["Next.js 16", "shadcn/ui", "Tailwind CSS", "Zod"],
      database: ["PostgreSQL 17"],
    },
    keyFeatures: [
      "Enterprise RBAC with fine-grained permission scopes",
      "Dynamic data table with column filtering and CSV export",
      "Zod-validated form generation components",
      "Pre-configured Docker Compose with backend and frontend",
    ],
    milestones: [
      { title: "FastAPI auth & token refresh pipeline", completed: true },
      { title: "Next.js 16 enterprise layout with breadcrumbs", completed: true },
      { title: "User & Role management module", completed: true },
      { title: "Audit log and event stream", completed: false },
    ],
    graphStats: { nodes: 96647, edges: 180000 },
    ports: [3012, 8007],
    path: "project-template/",
    quickCommands: [
      { label: "Frontend", cmd: "cd project-template/frontend && npm run dev" },
      { label: "Backend", cmd: "cd project-template/backend && uvicorn app.main:app --reload" },
    ],
    lastUpdated: "Aug 13",
  },
  {
    id: "yms",
    name: "YMS — Yard Management System",
    slug: "yms",
    category: "Full-Stack",
    description: "Logistics yard and dock scheduling management system for freight tracking, truck check-in, and trailer spot allocations.",
    longDescription: "Optimizes warehouse yard throughput by managing gate check-ins, dock appointment scheduling, yard spot allocations, and driver notifications.",
    progress: 65,
    status: "In Progress",
    priority: "Medium",
    techStack: {
      frontend: ["Next.js", "Tailwind CSS", "shadcn/ui", "TypeScript"],
      database: ["PostgreSQL 17"],
    },
    keyFeatures: [
      "Visual yard map with trailer parking spot status",
      "Dock door appointment booking calendar",
      "Driver gate pass QR code generation",
      "Detention fee tracking timer",
    ],
    milestones: [
      { title: "Yard spot & dock data models", completed: true },
      { title: "Gate check-in workflow UI", completed: true },
      { title: "Dock appointment calendar", completed: true },
      { title: "Realtime yard spot drag-and-drop map", completed: false },
    ],
    graphStats: { nodes: 542, edges: 1349 },
    ports: [3013],
    path: "yms/",
    quickCommands: [
      { label: "Dev Server", cmd: "cd yms && npm run dev" },
    ],
    lastUpdated: "Aug 09",
  },
  {
    id: "school-operations-system",
    name: "School Operations & Academic Suite",
    slug: "school-operations-system",
    category: "Full-Stack",
    description: "K-12 and university academic operations system with student attendance, grading books, course scheduling, and fee management.",
    longDescription: "Comprehensive school management suite for educators, students, and administrative staff. Handles classroom timetables, transcript calculations, and tuition invoices.",
    progress: 60,
    status: "In Progress",
    priority: "Medium",
    techStack: {
      backend: ["TypeScript", "NestJS", "Prisma"],
      frontend: ["Next.js", "shadcn/ui", "Tailwind CSS"],
      database: ["PostgreSQL 17"],
    },
    keyFeatures: [
      "Student information system (SIS) with parent details",
      "Classroom timetable scheduler with teacher conflict detection",
      "Automated grade GPA and transcript calculator",
      "Tuition fee billing and payment receipt generation",
    ],
    milestones: [
      { title: "Academic year & semester schema", completed: true },
      { title: "Student enrollment & attendance tracker", completed: true },
      { title: "Gradebook entry & calculation", completed: true },
      { title: "Student & parent mobile portal", completed: false },
    ],
    graphStats: { nodes: 2449, edges: 5500 },
    ports: [3014, 4002],
    path: "school-operations-system/",
    quickCommands: [
      { label: "Frontend", cmd: "cd school-operations-system/frontend && npm run dev" },
      { label: "Backend", cmd: "cd school-operations-system/backend && npm run start:dev" },
    ],
    lastUpdated: "Aug 07",
  },
  {
    id: "dinner-expense",
    name: "Dinner Expense — Instant Bill Splitter",
    slug: "dinner-expense",
    category: "Tools & Productivity",
    description: "Lightweight, instant restaurant bill splitter with itemized dish allocation, tip/tax sharing, and Khmer Bakong QR settlement.",
    longDescription: "Fast mobile-optimized web utility to split group restaurant checks with custom dish item assignments, service charges, tax distribution, and instant payment links.",
    progress: 90,
    status: "Production",
    priority: "Low",
    techStack: {
      frontend: ["Vue 3", "Vite", "Tailwind CSS", "TypeScript"],
    },
    keyFeatures: [
      "Itemized dish assigner (who ordered what)",
      "Proportional tax and service fee calculation",
      "Instant Bakong KHQR generator with exact amount",
      "Shareable bill summary screenshot and link",
    ],
    milestones: [
      { title: "Vue 3 interactive calculator core", completed: true },
      { title: "Tax and discount allocation algorithm", completed: true },
      { title: "Bakong QR generation integration", completed: true },
      { title: "Offline PWA service worker support", completed: true },
    ],
    graphStats: { nodes: 374, edges: 820 },
    ports: [5174],
    path: "dinner-expense/",
    quickCommands: [
      { label: "Dev Server", cmd: "cd dinner-expense && npm run dev" },
    ],
    lastUpdated: "Aug 05",
  },
  {
    id: "qa-studio",
    name: "QA Studio Automation Hub",
    slug: "qa-studio",
    category: "Tools & Productivity",
    description: "End-to-end QA testing workspace with automated Playwright suites, regression runners, and test report visualizations.",
    longDescription: "Centralized quality assurance suite providing automated visual regression testing, API test harnesses, and performance audit reports across monorepo applications.",
    progress: 65,
    status: "In Progress",
    priority: "Medium",
    techStack: {
      tools: ["Playwright", "TypeScript", "Allure Reports", "Docker"],
      frontend: ["Next.js", "Tailwind CSS"],
    },
    keyFeatures: [
      "Cross-browser automated E2E test suites (Chromium, Firefox, WebKit)",
      "Visual snapshot regression testing with pixel diffs",
      "API contract integration testing with automated mock data",
      "Interactive Allure test report web dashboard",
    ],
    milestones: [
      { title: "Playwright test runner configurations", completed: true },
      { title: "Rental & Foodie E2E critical path tests", completed: true },
      { title: "Automated CI test execution pipeline", completed: true },
      { title: "Load testing harness with k6 integration", completed: false },
    ],
    graphStats: { nodes: 427, edges: 980 },
    path: "qa-studio/",
    quickCommands: [
      { label: "Run E2E Tests", cmd: "cd qa-studio && npx playwright test" },
      { label: "Open UI Runner", cmd: "cd qa-studio && npx playwright test --ui" },
    ],
    lastUpdated: "Aug 06",
  },
  {
    id: "noesis",
    name: "Noesis — Knowledge & Note Engine",
    slug: "noesis",
    category: "Tools & Productivity",
    description: "Bi-directional Markdown knowledge graph and personal learning notebook with Obsidian sync and full-text search.",
    longDescription: "Personal second-brain knowledge management tool with [[wikilinks]], markdown rendering, tag taxonomy, and interactive graph relationship visualization.",
    progress: 75,
    status: "Active",
    priority: "Medium",
    techStack: {
      frontend: ["Next.js", "React", "Tailwind CSS", "KaTeX"],
      tools: ["D3.js Graph", "Gray-matter", "Shiki"],
    },
    keyFeatures: [
      "Bi-directional [[wikilink]] graph network",
      "Fast client-side full-text search with instant highlighting",
      "Mathematical formula rendering with KaTeX",
      "Obsidian vault two-way file synchronization",
    ],
    milestones: [
      { title: "Markdown parser with frontmatter & wikilinks", completed: true },
      { title: "Interactive D3 node connection graph", completed: true },
      { title: "Full-text indexing with Fuse.js", completed: true },
      { title: "AI note semantic clustering & auto-summarization", completed: false },
    ],
    graphStats: { nodes: 1262, edges: 2900 },
    ports: [3015],
    path: "noesis/",
    quickCommands: [
      { label: "Dev Server", cmd: "cd noesis && npm run dev" },
    ],
    lastUpdated: "Aug 04",
  },
  {
    id: "side-project",
    name: "Hand Sign Recognition (CV & ML)",
    slug: "side-project",
    category: "AI & Agents",
    description: "Real-time hand gesture and sign language recognition using MediaPipe hand tracking and machine learning classification.",
    longDescription: "Computer vision research application that captures video webcam feeds, extracts 21 3D hand landmarks, and classifies sign gestures with sub-20ms latency.",
    progress: 60,
    status: "Prototype",
    priority: "Low",
    techStack: {
      backend: ["Python 3.10", "OpenCV", "MediaPipe", "scikit-learn", "FastAPI"],
      frontend: ["Next.js", "WebRTC / Canvas"],
    },
    keyFeatures: [
      "21-Point 3D hand landmark coordinate extraction",
      "Real-time webcam video stream classification",
      "Dataset recording & landmark normalization tool",
      "Custom sign dictionary training pipeline",
    ],
    milestones: [
      { title: "MediaPipe hand landmark capture script", completed: true },
      { title: "Gesture dataset collection module", completed: true },
      { title: "Random Forest & SVM classifier training", completed: true },
      { title: "Web browser WebRTC live inference overlay", completed: false },
    ],
    graphStats: { nodes: 188, edges: 410 },
    ports: [8008],
    path: "side-project/",
    quickCommands: [
      { label: "Capture Data", cmd: "cd side-project && python collect_data.py" },
      { label: "Run Classifier", cmd: "cd side-project && python app.py" },
    ],
    lastUpdated: "Jul 28",
  },
  {
    id: "car-rental",
    name: "Car Rental & Vehicle Fleet",
    slug: "car-rental",
    category: "Full-Stack",
    description: "Vehicle reservation and fleet management system with driver dispatch, deposit tracking, and maintenance logs.",
    longDescription: "Fleet management system for car and motorcycle rental businesses. Features vehicle availability calendars, customer ID verification, insurance deposits, and mileage tracking.",
    progress: 70,
    status: "In Progress",
    priority: "Medium",
    techStack: {
      frontend: ["Next.js", "TypeScript", "shadcn/ui", "Tailwind CSS"],
      backend: ["Node.js", "Prisma"],
      database: ["PostgreSQL 17"],
    },
    keyFeatures: [
      "Vehicle fleet inventory (Sedan, SUV, Van, Motorbike)",
      "Interactive booking calendar with pickup/return time slots",
      "Driver license upload and deposit refund workflow",
      "Scheduled oil change and maintenance reminders",
    ],
    milestones: [
      { title: "Fleet data model & booking schema", completed: true },
      { title: "Reservation calendar with slot availability", completed: true },
      { title: "Customer rental agreement PDF generation", completed: true },
      { title: "GPS tracker live vehicle location", completed: false },
    ],
    graphStats: { nodes: 491, edges: 1150 },
    ports: [3016],
    path: "car-rental/",
    quickCommands: [
      { label: "Dev Server", cmd: "cd car-rental && npm run dev" },
    ],
    lastUpdated: "Aug 02",
  },
];
